language: csharp
mono: none
dotnet: 3.1
script:
 - dotnet restore
 - dotnet build --configuration Release --runtime win10-x64
 - zip -9 Forge/Server/bin/Release/netcoreapp3.1/win10-x64
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "win10-x64.zip"
  skip_cleanup: true
  draft: true